stages:
  - deploy

deploy:
  stage: deploy
  script:
    - aws eks --region us-east-2 update-kubeconfig --name dnamicro
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
    - kubectl apply -f k8s/canary-deployment.yaml
    - kubectl apply -f k8s/canary-service.yaml