apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-canary
  labels:
    app: whoami-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami-canary
  template:
    metadata:
      labels:
        app: whoami-canary
    spec:
      containers:
      - name: whoami-canary
        image: emilevauge/whoami:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-canary-service
spec:
  selector:
    app: whoami-canary
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP