apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-canary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami-canary
  template:
    metadata:
      labels:
        app: whoami-canary
    spec:
      containers:
      - name: whoami-canary
        image: emilevauge/whoami:latest
        ports:
        - containerPort: 80