apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami-nodejs
  template:
    metadata:
      labels:
        app: whoami-nodejs
    spec:
      containers:
      - name: whoami-nodejs
        image: congtaojiang/whoami-nodejs-express:latest
        ports:
        - containerPort: 8080