apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  labels:
    app: whoami-nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami-nodejs
  template:
    metadata:
      labels:
        app: whoami-nodejs
    spec:
      containers:
      - name: whoami-nodejs
        image: congtaojiang/whoami-nodejs-express:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
spec:
  selector:
    app: whoami-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer