apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-nodejs
        image: congtaojiang/whoami-nodejs-express
        ports:
        - containerPort: 80
